version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d # to update vhost configuration
      - /usr/share/nginx/html # to write challenge files
      - "../../../volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - app

  # MongoDb services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - app

  # Backend services
  auth_service:
    image: jwilder/whoami
    build: /auth
    container_name: dev_compiler_auth
    ports:
      - 3001:80
    # expose:                 # <--- the important bit here
    #   - "8000"              # <--- and here
    volumes:
      - .:/user/src/app/dev-compiler-backend/auth
    environment: 
      - VIRTUAL_HOST=api.dev-compiler.com
      - VIRTUAL_PORT=3001
      - VIRTUAL_PATH=/api/auth
      - ENABLE_IPV6=true
      - APP_PORT=3001
      - APP_NAME=AUTH_SERVER
      - PINO_LOG_LEVEL=info
      - ENABLE_CONSOLE_LOG=true
      - MONGO_URI=mongodb://mongo_db:27017/AUTH_SERVER
      - MONGO_DB_PORT=27017
      - ENVIRONMENT=DEVELOPMENT
    depends_on:
      - mongo_db
      - nginx-proxy
    networks:
      - app

volumes:
  mongo_db: {}

networks:
  app: 
