version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d # to update vhost configuration
      - /usr/share/nginx/html # to write challenge files
      - "../../../volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - app

  # MongoDb services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - app

  # Backend services
  auth_service:
    image: jwilder/whoami:auth
    build: ./auth
    container_name: auth_service_container
    ports:
      - 3001:3001
    # expose:                 # <--- the important bit here
    #   - "3001"              # <--- and here
    volumes:
      - auth_app:/app/auth
      - auth_config:/config
    environment: 
      - VIRTUAL_HOST=api.dev-compiler.com
      - VIRTUAL_PORT=3001
      - VIRTUAL_PATH=/api/auth
      - ENABLE_IPV6=true
      - APP_PORT=3001
      - APP_NAME=AUTH_SERVER
      - PINO_LOG_LEVEL=info
      - ENABLE_CONSOLE_LOG=true
      - MONGO_URI=mongodb://mongo_db:27017/AUTH_SERVER
      - MONGO_DB_PORT=27017
      - ENVIRONMENT=local
      - NODE_ENV=DEVELOPMENT
      - COOKIE_SECRET="khjgfdryuti(*&*^&%^$tfghvjjUTYRTSDHF457654"
      - JWT_SECRET="LKJHGFDSFGUI(*&*^&%^$%&*(hjbnhgjhfg%^&*&^Y6875676"
    depends_on:
      - mongo_db
      - nginx-proxy
      - terminal_service
    networks:
      - app
    labels:
      - "com.compiler.service=auth"
  terminal_service:
    image: jwilder/whoami:terminal
    build: ./terminal
    container_name: terminal_service_container
    ports:
      - 3002:3002
    # expose:                 # <--- the important bit here
    #   - "3001"              # <--- and here
    volumes:
      - terminal_app:/app/terminal
      - terminal_logs:/logs
    environment: 
      - VIRTUAL_HOST=api.dev-compiler.com
      - VIRTUAL_PORT=3002
      - VIRTUAL_PATH=/api/terminal
      - ENABLE_IPV6=true
      - APP_PORT=3002
      - APP_NAME=TERMINAL_SERVER
      - PINO_LOG_LEVEL=info
      - ENABLE_CONSOLE_LOG=true
      - MONGO_URI=mongodb://mongo_db:27017/TERMINAL_SERVER
      - MONGO_DB_PORT=27017
      - ENVIRONMENT=local
      - NODE_ENV=DEVELOPMENT
      - COOKIE_SECRET="khjgfdryuti(*&*^&%^$tfghvjjUTYRTSDHF457654"
      - JWT_SECRET="LKJHGFDSFGUI(*&*^&%^$%&*(hjbnhgjhfg%^&*&^Y6875676"
    depends_on:
      - mongo_db
      - nginx-proxy
    networks:
      - app
    labels:
      - "com.compiler.service=terminal"
volumes:
  mongo_db: {}
  auth_app:
  auth_config:
  terminal_app:
  terminal_logs:

networks:
  app:
    external: false
